"""
Danh sach 40 tu (8 chu de x 5 tu) dang dung trong app CalmLearn - copy nguyen van
tu app/src/main/java/com/education/calmlearn/data/mock/MockData.kt (khong doi id,
khong doi noi dung) de:

1. Lam SEED LIST cho ETL: gioi han pham vi 4 nguon (OEWN/CEFR-J/CEFR-Annotated
   WordNet/Tatoeba) dung 40 lemma nay o Phase 1 (dung theo yeu cau "bat dau bang
   cac tu da xuat hien trong app hien tai" - xem CalmLearn/SQLITE_VOCAB.md).
2. Cung cap "legacy" meaning_vi/phonetic (2 truong 4 nguon KHONG co) + dung lam
   fallback English definition/example cho nhung tu OEWN/Tatoeba khong co du
   lieu (vd cum tu nhieu am tiet nhu "boarding pass" thuong khong co synset
   rieng trong WordNet) - moi truong fallback nay duoc gan source ro rang trong
   build_dataset.py, KHONG tron lan voi du lieu tu 4 nguon that.

id giu dung dinh dang "<topicId>_<n>" vi ProgressRepository (Firestore) dang luu
learnedWordIds/favoriteWordIds theo dung cac id nay cho tai khoan da co san du
lieu - doi id se lam mat tuong thich voi du lieu Firestore cu.
"""

SEED_WORDS = [
    # topic: travel
    dict(id="travel_1", topic_id="travel", word="journey", phonetic="/ˈdʒɜːni/", pos="n.",
         meaning_vi="hành trình, chuyến đi",
         definition_en="a trip from one place to another, especially a long one",
         example_en="Our journey to the mountains took six hours.",
         example_vi="Hành trình của chúng tôi đến vùng núi mất sáu tiếng.",
         synonyms=["trip", "voyage"]),
    dict(id="travel_2", topic_id="travel", word="itinerary", phonetic="/aɪˈtɪnərəri/", pos="n.",
         meaning_vi="lịch trình",
         definition_en="a planned route or schedule for a journey",
         example_en="She emailed everyone the full itinerary before the trip.",
         example_vi="Cô ấy đã gửi email lịch trình đầy đủ cho mọi người trước chuyến đi.",
         synonyms=["schedule", "plan"]),
    dict(id="travel_3", topic_id="travel", word="luggage", phonetic="/ˈlʌɡɪdʒ/", pos="n.",
         meaning_vi="hành lý",
         definition_en="bags and suitcases used to carry belongings while travelling",
         example_en="Please keep your luggage with you at all times.",
         example_vi="Vui lòng giữ hành lý bên mình mọi lúc.",
         synonyms=["baggage"]),
    dict(id="travel_4", topic_id="travel", word="boarding pass", phonetic="/ˈbɔːdɪŋ pɑːs/", pos="n.",
         meaning_vi="thẻ lên máy bay",
         definition_en="a document allowing a passenger to board a flight",
         example_en="Don't forget to show your boarding pass at the gate.",
         example_vi="Đừng quên xuất trình thẻ lên máy bay tại cổng.",
         synonyms=["ticket"]),
    dict(id="travel_5", topic_id="travel", word="delay", phonetic="/dɪˈleɪ/", pos="n./v.",
         meaning_vi="sự trì hoãn / trì hoãn",
         definition_en="a period of time when something is later than expected",
         example_en="The train delay made us miss our connection.",
         example_vi="Sự trì hoãn của tàu khiến chúng tôi lỡ chuyến nối tiếp.",
         synonyms=["postponement"]),

    # topic: daily
    dict(id="daily_1", topic_id="daily", word="routine", phonetic="/ruːˈtiːn/", pos="n.",
         meaning_vi="thói quen hằng ngày",
         definition_en="the usual series of things you do at a particular time",
         example_en="Waking up at 6 AM is part of my daily routine.",
         example_vi="Thức dậy lúc 6 giờ sáng là một phần thói quen hằng ngày của tôi.",
         synonyms=["habit"]),
    dict(id="daily_2", topic_id="daily", word="chore", phonetic="/tʃɔːr/", pos="n.",
         meaning_vi="việc vặt",
         definition_en="a routine task, especially a household one",
         example_en="Washing dishes is my least favorite chore.",
         example_vi="Rửa bát là việc vặt tôi ít thích nhất.",
         synonyms=["task"]),
    dict(id="daily_3", topic_id="daily", word="errand", phonetic="/ˈerənd/", pos="n.",
         meaning_vi="việc lặt vặt cần đi ra ngoài",
         definition_en="a short trip to do a specific task, like shopping",
         example_en="I need to run a few errands this afternoon.",
         example_vi="Chiều nay tôi cần đi làm vài việc lặt vặt.",
         synonyms=["task"]),
    dict(id="daily_4", topic_id="daily", word="commute", phonetic="/kəˈmjuːt/", pos="v./n.",
         meaning_vi="đi lại (giữa nhà và nơi làm)",
         definition_en="to travel regularly between home and work",
         example_en="She commutes to the city by bus every day.",
         example_vi="Cô ấy đi làm bằng xe buýt vào thành phố mỗi ngày.",
         synonyms=["travel"]),
    dict(id="daily_5", topic_id="daily", word="leisure", phonetic="/ˈleʒər/", pos="n.",
         meaning_vi="thời gian rảnh rỗi",
         definition_en="time spent doing what you enjoy, not working",
         example_en="He spends his leisure time reading novels.",
         example_vi="Anh ấy dành thời gian rảnh để đọc tiểu thuyết.",
         synonyms=["free time"]),

    # topic: food
    dict(id="food_1", topic_id="food", word="appetizer", phonetic="/ˈæpɪtaɪzər/", pos="n.",
         meaning_vi="món khai vị",
         definition_en="a small dish served before the main course",
         example_en="We shared an appetizer while waiting for the main dish.",
         example_vi="Chúng tôi dùng chung một món khai vị trong lúc chờ món chính.",
         synonyms=["starter"]),
    dict(id="food_2", topic_id="food", word="reservation", phonetic="/ˌrezərˈveɪʃn/", pos="n.",
         meaning_vi="sự đặt chỗ",
         definition_en="an arrangement to have a table, room, etc. kept for you",
         example_en="I made a reservation for two at 7 PM.",
         example_vi="Tôi đã đặt chỗ cho hai người lúc 7 giờ tối.",
         synonyms=["booking"]),
    dict(id="food_3", topic_id="food", word="recipe", phonetic="/ˈresəpi/", pos="n.",
         meaning_vi="công thức nấu ăn",
         definition_en="a set of instructions for preparing a dish",
         example_en="This is my grandmother's recipe for spring rolls.",
         example_vi="Đây là công thức làm chả giò của bà tôi.",
         synonyms=["formula"]),
    dict(id="food_4", topic_id="food", word="bland", phonetic="/blænd/", pos="adj.",
         meaning_vi="nhạt, ít gia vị",
         definition_en="having little or no flavor",
         example_en="The soup tasted a bit bland without salt.",
         example_vi="Món súp có vị hơi nhạt khi thiếu muối.",
         synonyms=["tasteless"]),
    dict(id="food_5", topic_id="food", word="leftovers", phonetic="/ˈleftoʊvərz/", pos="n.",
         meaning_vi="đồ ăn thừa",
         definition_en="food remaining after a meal",
         example_en="We kept the leftovers in the fridge for tomorrow.",
         example_vi="Chúng tôi để đồ ăn thừa trong tủ lạnh cho ngày mai.",
         synonyms=["remains"]),

    # topic: tech
    dict(id="tech_1", topic_id="tech", word="upgrade", phonetic="/ˈʌpɡreɪd/", pos="v./n.",
         meaning_vi="nâng cấp",
         definition_en="to improve a device or system to a better version",
         example_en="I upgraded my phone's storage last week.",
         example_vi="Tôi đã nâng cấp dung lượng lưu trữ điện thoại tuần trước.",
         synonyms=["update"]),
    dict(id="tech_2", topic_id="tech", word="battery life", phonetic="/ˈbætəri laɪf/", pos="n.",
         meaning_vi="thời lượng pin",
         definition_en="how long a device runs before needing a charge",
         example_en="This laptop has excellent battery life.",
         example_vi="Chiếc laptop này có thời lượng pin rất tốt.",
         synonyms=["charge duration"]),
    dict(id="tech_3", topic_id="tech", word="malware", phonetic="/ˈmælwer/", pos="n.",
         meaning_vi="phần mềm độc hại",
         definition_en="software designed to damage or disrupt a system",
         example_en="The download contained hidden malware.",
         example_vi="Tệp tải xuống chứa phần mềm độc hại ẩn.",
         synonyms=["virus"]),
    dict(id="tech_4", topic_id="tech", word="password", phonetic="/ˈpæswɜːrd/", pos="n.",
         meaning_vi="mật khẩu",
         definition_en="a secret word or phrase used to access an account",
         example_en="Never share your password with anyone.",
         example_vi="Đừng bao giờ chia sẻ mật khẩu của bạn với bất kỳ ai.",
         synonyms=["passcode"]),
    dict(id="tech_5", topic_id="tech", word="device", phonetic="/dɪˈvaɪs/", pos="n.",
         meaning_vi="thiết bị",
         definition_en="a piece of equipment made for a particular purpose",
         example_en="Please turn off all electronic devices before takeoff.",
         example_vi="Vui lòng tắt tất cả thiết bị điện tử trước khi cất cánh.",
         synonyms=["gadget"]),

    # topic: school
    dict(id="school_1", topic_id="school", word="assignment", phonetic="/əˈsaɪnmənt/", pos="n.",
         meaning_vi="bài tập được giao",
         definition_en="a task or piece of work given to someone",
         example_en="The assignment is due next Monday.",
         example_vi="Bài tập phải nộp vào thứ Hai tới.",
         synonyms=["homework"]),
    dict(id="school_2", topic_id="school", word="lecture", phonetic="/ˈlektʃər/", pos="n.",
         meaning_vi="bài giảng",
         definition_en="an educational talk to an audience",
         example_en="The professor gave a two-hour lecture on economics.",
         example_vi="Giáo sư đã giảng bài hai tiếng về kinh tế học.",
         synonyms=["class"]),
    dict(id="school_3", topic_id="school", word="scholarship", phonetic="/ˈskɒlərʃɪp/", pos="n.",
         meaning_vi="học bổng",
         definition_en="financial aid given to a student for their studies",
         example_en="She received a full scholarship to study abroad.",
         example_vi="Cô ấy được nhận học bổng toàn phần để du học.",
         synonyms=["grant"]),
    dict(id="school_4", topic_id="school", word="deadline", phonetic="/ˈdedlaɪn/", pos="n.",
         meaning_vi="hạn chót",
         definition_en="the latest time by which something must be finished",
         example_en="The submission deadline is Friday at noon.",
         example_vi="Hạn nộp bài là trưa thứ Sáu.",
         synonyms=["due date"]),
    dict(id="school_5", topic_id="school", word="campus", phonetic="/ˈkæmpəs/", pos="n.",
         meaning_vi="khuôn viên trường",
         definition_en="the grounds and buildings of a university",
         example_en="The campus has a large library and a sports center.",
         example_vi="Khuôn viên trường có thư viện lớn và trung tâm thể thao.",
         synonyms=["grounds"]),

    # topic: work
    dict(id="work_1", topic_id="work", word="resume", phonetic="/ˈrezʊmeɪ/", pos="n.",
         meaning_vi="sơ yếu lý lịch",
         definition_en="a document summarizing your work experience and skills",
         example_en="Update your resume before applying for the job.",
         example_vi="Hãy cập nhật sơ yếu lý lịch trước khi ứng tuyển.",
         synonyms=["CV"]),
    dict(id="work_2", topic_id="work", word="candidate", phonetic="/ˈkændɪdət/", pos="n.",
         meaning_vi="ứng viên",
         definition_en="a person who applies for a job",
         example_en="Three candidates were shortlisted for the interview.",
         example_vi="Ba ứng viên đã được chọn vào vòng phỏng vấn.",
         synonyms=["applicant"]),
    dict(id="work_3", topic_id="work", word="deadline", phonetic="/ˈdedlaɪn/", pos="n.",
         meaning_vi="hạn chót",
         definition_en="the latest time a task must be completed",
         example_en="We must meet the project deadline this Friday.",
         example_vi="Chúng ta phải hoàn thành dự án đúng hạn thứ Sáu này.",
         synonyms=["due date"]),
    dict(id="work_4", topic_id="work", word="promotion", phonetic="/prəˈmoʊʃn/", pos="n.",
         meaning_vi="sự thăng chức",
         definition_en="advancement to a higher position at work",
         example_en="He got a promotion after two years at the company.",
         example_vi="Anh ấy được thăng chức sau hai năm làm việc tại công ty.",
         synonyms=["advancement"]),
    dict(id="work_5", topic_id="work", word="colleague", phonetic="/ˈkɒliːɡ/", pos="n.",
         meaning_vi="đồng nghiệp",
         definition_en="a person you work with",
         example_en="My colleague helped me finish the report.",
         example_vi="Đồng nghiệp của tôi đã giúp tôi hoàn thành báo cáo.",
         synonyms=["coworker"]),

    # topic: social
    dict(id="social_1", topic_id="social", word="acquaintance", phonetic="/əˈkweɪntəns/", pos="n.",
         meaning_vi="người quen",
         definition_en="someone you know but not closely",
         example_en="He's just a business acquaintance, not a close friend.",
         example_vi="Anh ấy chỉ là người quen trong công việc, không phải bạn thân.",
         synonyms=["contact"]),
    dict(id="social_2", topic_id="social", word="apologize", phonetic="/əˈpɒlədʒaɪz/", pos="v.",
         meaning_vi="xin lỗi",
         definition_en="to say sorry for something you did wrong",
         example_en="She apologized for being late to the meeting.",
         example_vi="Cô ấy đã xin lỗi vì đến trễ cuộc họp.",
         synonyms=["say sorry"]),
    dict(id="social_3", topic_id="social", word="compliment", phonetic="/ˈkɒmplɪmənt/", pos="n./v.",
         meaning_vi="lời khen / khen ngợi",
         definition_en="an expression of praise or admiration",
         example_en="He complimented her on the excellent presentation.",
         example_vi="Anh ấy khen cô ấy về bài thuyết trình xuất sắc.",
         synonyms=["praise"]),
    dict(id="social_4", topic_id="social", word="invite", phonetic="/ɪnˈvaɪt/", pos="v.",
         meaning_vi="mời",
         definition_en="to ask someone to attend an event",
         example_en="We invited our neighbors to the housewarming party.",
         example_vi="Chúng tôi mời hàng xóm đến tiệc tân gia.",
         synonyms=["ask"]),
    dict(id="social_5", topic_id="social", word="gathering", phonetic="/ˈɡæðərɪŋ/", pos="n.",
         meaning_vi="buổi tụ họp",
         definition_en="an occasion when people come together",
         example_en="The family gathering happens every Lunar New Year.",
         example_vi="Buổi tụ họp gia đình diễn ra vào mỗi dịp Tết.",
         synonyms=["get-together"]),

    # topic: movie
    dict(id="movie_1", topic_id="movie", word="plot", phonetic="/plɒt/", pos="n.",
         meaning_vi="cốt truyện",
         definition_en="the main events of a story",
         example_en="The plot twist at the end surprised everyone.",
         example_vi="Tình tiết bất ngờ ở cuối phim khiến mọi người ngạc nhiên.",
         synonyms=["storyline"]),
    dict(id="movie_2", topic_id="movie", word="subtitle", phonetic="/ˈsʌbtaɪtl/", pos="n.",
         meaning_vi="phụ đề",
         definition_en="translated text shown on screen during a film",
         example_en="I watched the film with English subtitles.",
         example_vi="Tôi đã xem phim với phụ đề tiếng Anh.",
         synonyms=["caption"]),
    dict(id="movie_3", topic_id="movie", word="sequel", phonetic="/ˈsiːkwəl/", pos="n.",
         meaning_vi="phần tiếp theo",
         definition_en="a film that continues the story of an earlier one",
         example_en="The sequel was even better than the original.",
         example_vi="Phần tiếp theo còn hay hơn cả bản gốc.",
         synonyms=["follow-up"]),
    dict(id="movie_4", topic_id="movie", word="cast", phonetic="/kæst/", pos="n.",
         meaning_vi="dàn diễn viên",
         definition_en="the actors who perform in a film",
         example_en="The cast includes several award-winning actors.",
         example_vi="Dàn diễn viên gồm nhiều diễn viên từng đoạt giải.",
         synonyms=["actors"]),
    dict(id="movie_5", topic_id="movie", word="premiere", phonetic="/prɪˈmɪər/", pos="n.",
         meaning_vi="buổi công chiếu",
         definition_en="the first public showing of a film",
         example_en="Fans lined up outside the premiere all night.",
         example_vi="Người hâm mộ xếp hàng bên ngoài buổi công chiếu suốt đêm.",
         synonyms=["opening"]),
]

VI_SOURCE_LABEL = "CalmLearn (bien soan thu cong, ngoai 4 nguon ETL)"
